### ISSUE TITLE
Investigate removing hard-coded dependency on node_modules

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-react-native#11]
See the [yarnrc.yml](example/.yarnrc.yml) and [Podfile](example/ios/Podfile) in the example project. It looks like the current approach is to hard-code path dependencies, which feels like a code smell to me, and further assumes that the end user will always be using `npm` or some other package manager in a legacy compatibility mode, and this is suboptimal at best.

**Comment by ianthetechie** [comment]
Tagging with help-wanted since I almost assuredly lack the knowledge to know if this is even a reasonable request. It's also pretty baked as an android assumption too.

**Comment by jthiard** [comment]
I'm not sure react-native has good support for PNP installs right now. Will take a closer look.

**Comment by jthiard** [comment]
See react-native-community/cli#27 for some context. PnP support looks like is not implemented in react-native and not a priority at this time.

I just tried to bootstrap a react native app with react native 0.70.6 and found the same hard-coded references to `node_modules` in ios `Podfile`, but also in android `build.gradle`. See in the example app: 
https://github.com/maplibre/maplibre-react-native/blob/e6dffb21c34648ad4924ccd6ed5d22fe2a1fe38e/example/android/build.gradle#L29

So in my opinion there isn't much we can do to remove it at this time.

**Comment by ianthetechie** [comment]
Yeah, makes sense. Thanks a bunch for the research on this.

I've been able to bootstrap projects that install the `maplibre-react-native` package locally (via yalc) just fine, as well as the examples, so it's probably not an issue using pnp for the development of the module itself as it's all packaged the same at the end of the day (IIUC), but it looks like we can't get around the hard dependency on a `node_modules` folder for actual apps at the end of the day. And I guess that's not a huge issue since nobody except me really cares ;)
