### ISSUE TITLE
Map performance drops on Android when keyboard is open

### ISSUE THREAD

**Issue by JDBoots** [maplibre/maplibre-react-native#135]
Hi there, 

We're encountering some performance issues when combining MapLibre with a simple TextInput. At first panning and zooming is very smooth, but when the keyboard is open, the map starts to stutter quite a bit, and it also keeps stuttering after closing the keyboard again (see video attached).

Here's the minimal component from the video:

 ```
import React from 'react';
import { View } from 'react-native';
import MapLibreGL from '@maplibre/maplibre-react-native';
import { TextInput } from 'react-native-gesture-handler';

const LibreMap = () => {
  return (
    <View style={[{ flex: 1 }]}>
      <MapLibreGL.MapView
        style={{ flex: 1 }}
        key={'maplibre'}
        logoEnabled={false}
        attributionEnabled={false}
        compassEnabled={true}
        pitchEnabled={true}
      />

      <TextInput />
    </View>
  );
};

export default LibreMap;
```

https://github.com/maplibre/maplibre-react-native/assets/125256202/3f13bb66-8c1e-4d80-9884-23c226f55061

Any ideas on how to improve this? :)

Thanks in advance for any help!

**Comment by JDBoots** [comment]
After some more testing, it seems like the above only happens when the component is rendered within a native stack. When we render it outside of a native stack navigator it keeps performing smoothly, so this seems to be an issue in combination with with @react-navigation/native-stack.

**Comment by tyrauber** [comment]
@JDBoots, which version of @react-navigation? It also might be related to react-native-reanimated.  Can you provide a breakdown of your dependencies?

**Comment by JDBoots** [comment]
Hey @tyrauber, sorry for the late reply, our issue may be related to other things in our app after all - when we stop rendering other tabs in the background, the performance is a lot better. Still I think it's interesting that the performance drops after one  rerender of the component where the map is mounted, however for us it's not really an urgent issue anymore so I'll close this issue for now.
