### ISSUE TITLE
No Apple Silicon support?

### ISSUE THREAD

**Issue by MariuzM** [maplibre/maplibre-react-native#136]
I have followed this guide https://github.com/maplibre/maplibre-react-native/blob/main/plugin/install.md for my Expo SDK49 project. 

But once i start it i get error 

```
❌  (ios/Pods/Target Support Files/Pods-ExpoStarterApp/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/marius/Library/Developer/Xcode/DerivedData/ExpoStarterApp-ertpvmwddbzkrpfstyipblvrgkli/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import ExpoBlur
  10 | import EXConstants
  11 | import EASClient
```

I dont have this issue with `React Native Mapbox` package. I'm running on M1 Max

**Comment by tyrauber** [comment]
@MariuzM,  Try opening up the workspace in Xcode and check the valid architectures and disabled architectures. Make sure  ARM isn't disabled. I've run into this before after an expo prebuild.

**Comment by MariuzM** [comment]
@tyrauber how can i tell what is disabled? 

<img width="491" alt="image" src="https://github.com/maplibre/maplibre-react-native/assets/36937039/9a212b50-7fe4-4bd6-b27f-694bba76e711">

**Comment by tyrauber** [comment]
It's the section under Excluded Architectures. Debug > Any iOS Simulator SDK. 

This looks ok. It doesn't state ARM.
