### ISSUE TITLE
Clean up default style specification

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-react-native#14]
Upstream on iOS falls back to the MapLibre demo tiles. However, Android will crash with a random exception.

The Android framework currently also has a place in the OfflineManager where a default is defined. I currently address the exception issue above by importing this in another module, which is a bit of a code smell. It seems like we should probably just extract this elsewhere.

**Comment by KiwiKilian** [comment]
Fixed through #559. The `DEFAULT_STYLE_URL` is now inside the `MLRNModule`.
