### ISSUE TITLE
Maptiles using AWS Location with ESRI provider is messed up on Android

### ISSUE THREAD

**Issue by opakholis** [maplibre/maplibre-react-native#159]
### Steps to Trigger Behavior

1. Clone the repo.
2. Open [AWS Location](https://aws.amazon.com/location/) and create a new Map with the style "Esri Light" and grab the credentials needed.
3. Run the project.

### Link to Minimal Reproducible Example

https://github.com/opakholis/maplibre-aws-reproduce

### Expected Behavior

The same as in the iOS screenshot below

![simulator_screenshot_61BDA304-6A1C-4E7E-9188-B3FE49CBB58D](https://github.com/maplibre/maplibre-react-native/assets/49778014/0d02770c-8f63-4cd2-b38c-ccd59e6a12e0)

### Actual Behavior

![Screenshot_1699250919](https://github.com/maplibre/maplibre-react-native/assets/49778014/b349e060-19de-48e4-80be-91caa3fc212c)

### Screenshots (if applicable)

![CleanShot 2023-11-06 at 1 09 26](https://github.com/maplibre/maplibre-react-native/assets/49778014/606482e4-bbe6-4cd1-8fac-133afeb8d1d3)

### Version(s) affected

- Platform: Android
- OS version: Android 13
- Device type: Xioami Redmi Note 11, Emulator Pixel 4
- Emulator/ Simulator: yes
- Development OS: MacOS 13.6
- maplibre-react-native Version ^9.1.0, 9.0.1
- MapLibre GL version [e.g. 6.3.0]
- React Native Version 0.72.6, 0.71.13

### Additional context

cc @ianthetechie

**Comment by jthiard** [comment]
Just in case, do you have the same behavior on a real android device  ?
I ask this because I've always seen those black glitches on the android emulator (and only on the android emulator) when working with mapbox native & rnmapbox, or maplibre native and maplibre-react-native.
But I never saw it on a real device, and never had a complaint from a real user.

**Comment by opakholis** [comment]
@jthiard Of course, I've also tried running it on my physical device (Redmi Note 11) and the result is the same

**Comment by mojodna** [comment]
This is a known issue on the Amazon Location side: this style doesn't have a background color specified, so you're seeing the background color of the view behind it leaking through. You should be able to work around it by specifying a background color (`#f2f3f3` to match the intent) on the map view or on a view directly behind it.

**Comment by ianthetechie** [comment]
Thanks for chiming in @mojodna. That immediately makes sense to me. I'm not sure there's anything we can/should do about this in any of the MapLibre projects, so I'll go ahead and close this issue.
