### ISSUE TITLE
Fix plugin build

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-react-native#16]
Running `yarn build:plugin` currently doesn't work. I'm not sure if we forked in a broken state or if I ended up breaking something while attempting to modernize the project and rip out mapbox. This will block #2.

**Comment by jthiard** [comment]
Looks like another "PnP" problem :laughing: 

But playing around a bit I think we may end up with a solution for this one too. I'll let you know as soon as I'm confident.

**Comment by jthiard** [comment]
Should be fixed by PR #17
