### ISSUE TITLE
Figure out why the iOS / Android CI actions aren't showing as run

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-react-native#19]
Noticed this when looking at the badges in the README. Probably a simple misconfiguration or quirk of how the jobs are imported right now (inherited from upstream).

**Comment by sarahsporck** [comment]
Probably because iOS and Android CI aren't run at all. I guess the trigger is not defined correctly, isn't it?

**Comment by KiwiKilian** [comment]
Fixed by #535
