### ISSUE TITLE
Error: Crash with Android emulator

### ISSUE THREAD

**Issue by carlleton** [maplibre/maplibre-react-native#198]
It's crash with the Android emulator,but it's all right on the real device.
It's show the base map, when I move it, then it crash.

### Steps to Trigger Behavior

1. flow the android install, `MapLibreGL.setAccessToken(null);`
2. use the basic example
```jsx
<MapLibreGL.MapView
        style={styles.map}
        attributionEnabled={false}
        logoEnabled={false}
        styleURL="https://demotiles.maplibre.org/style.json"
      />
```
3. yarn run android

used Android 14, API 34

**Comment by KiwiKilian** [comment]
I had a good experience lately with the emulator. You can try again with the latest v10 pre-releases or try to update you emulator setup.
