### ISSUE TITLE
Metal support on iOS

### ISSUE THREAD

**Issue by lmeier** [maplibre/maplibre-react-native#228]
I saw the awesome news that the [latest MapLibre iOS](https://github.com/maplibre/maplibre-gl-native-distribution/releases/tag/6.0.0) supports Metal for rendering. Is an upgrade of the iOS dependency to 6.0.0 planned soon? Really excited to see the improved rendering performance!

**Comment by dehret** [comment]
I need this upgrade for one of my projects, too.

Is someone already working on this? I have not seen any activity of this so far, but want to double check before diving into making the necessary changes myself.

**Comment by tyrauber** [comment]
Hi @dehret, no one is working on it at the moment, that I am aware of.  Would love the help. We need to update to use both the latest Android and iOS SDKs, but they contain significant changes to the API.

**Comment by louwers** [comment]
There are not that many API changes.

**Comment by sjchristi** [comment]
Anyone attempting this right now?  If someone could give me pointers or advice or even a PR for this in the past I can attempt it.

**Comment by dehret** [comment]
I haven't had the time yet to start working on this @sjchristi. I also have not contributed to this project, yet, so it might take me quite some time to get up to speed. So feel free to start with your attempt.

**Comment by louwers** [comment]
You need to update the dependencies similar to https://github.com/maplibre/maplibre-react-native/commit/d3a9743a0880f75959052ba331ee3a288c3e7525

**Comment by louwers** [comment]
There are no API changes.

**Comment by sjchristi** [comment]
ok, thank you for the help.  wish me luck 👍

**Comment by sjchristi** [comment]
Making progress...  I have the sample app up and running on 6.4.0:

https://github.com/iOverlander/maplibre-react-native/tree/maplibre-native-6.4

Question (not sure who's in charge here?) - should I be renaming the react native layer -- `RCTMGL*` -- to `RCTMLN*`?

**Comment by sjchristi** [comment]
Brought the fork mentioned above into my project, and simulator runs and renders beautifully, no crashes.  Here's the diff:  

https://github.com/maplibre/maplibre-react-native/compare/main...iOverlander:maplibre-react-native:maplibre-native-6.4?expand=1

I'm running into an issue - The `husky install` line that was added does not work for me.  I get a `command not found` error.  Was unable resolve this after an hour of hunting around for what might be wrong..  so I just removed it as a temp workaround.  I'm not sure whats unique about my environment as to why I can't get this working :(.

**Comment by tyrauber** [comment]
> Making progress... I have the sample app up and running on 6.4.0:
> 
> https://github.com/iOverlander/maplibre-react-native/tree/maplibre-native-6.4
> 
> Question (not sure who's in charge here?) - should I be renaming the react native layer -- `RCTMGL*` -- to `RCTMLN*`?

Awesome! Yeah, I would think we should rename the class to `RCTMLN*` to be consistent, no?  Don't worry about husky. Let's just get it building with the new iOS SDK and metal. If it lints and tests pass let's get it merged.

**Comment by sjchristi** [comment]
Ok, will tackle the RCTMLN* rename.  I think it's the right thing to do.

**Comment by sjchristi** [comment]
Ok, rename is done and pushed.  Example app was working in both ios and android (i renamed both) when I tested.

**Comment by sjchristi** [comment]
I'd like to run tests but I'm not sure.  I noticed this is perhaps still an issue:  https://github.com/maplibre/maplibre-react-native/issues/22

If anyone could give me an overview of how to run tests I will try that here.

**Comment by sjchristi** [comment]
Was wondering if I should be upgrading Android as well, but as far as I can tell it looks like this is using a rather recent version so I think it's ok (It appears it's using 10.2; latest is 10.3).

**Comment by tyrauber** [comment]
@sjchristi, Android was upgrading recently. We should definitely bump to a newer version, but I would do that in a separate branch. In regards to running lint and tests, just run `yarn lint` and `yarn tests` from root.
