### ISSUE TITLE
Figure out Detox and why it's so slow

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-react-native#23]
Local iOS builds are super fast, but the Detox build is super slow and the tests sometimes fail. Tangentially related to #22, we need to understand what's going on here as this was inherited from upstream. Going through their guides (https://wix.github.io/Detox/docs/introduction/project-setup/), I don't see a `.detoxrc.js`, so I'm not sure if we're even using it correctly, nor what the tests actually do at the moment.

Also curiously, it claims to be a cross-platform framework, but it's only integrated into the iOS CI actions. If this is providing a real benefit, we should probably get it running on Android as well.

**Comment by ianthetechie** [comment]
Oops :D Forgot that action existed....

**Comment by sarahsporck** [comment]
The tests currently only start the example app and check whether components are rendered in the root page. So basically they don't test the actual maplibre functionality atm. What does make sense though that it is building the app (at least for ios) in the CI.
Starting detox v20 the config became a little bit simpler. Check out [this PR](https://github.com/maplibre/maplibre-react-native/pull/207) to see what changed.

**Comment by KiwiKilian** [comment]
Fixed by #535
