### ISSUE TITLE
Could not find com.facebook.react:react-android

### ISSUE THREAD

**Issue by dellta1291** [maplibre/maplibre-react-native#231]
hi 
 use this package  in react native 0.64.4  and react native + 0.60.0    has error

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app > project :maplibre_maplibre-react-native
         
help me how to fix it  
thank you

**Comment by sarahsporck** [comment]
Nice! We'd definitely apreciate you're help!

**Comment by KiwiKilian** [comment]
A similar fix proposed here was released on [v10.0.0-beta.6](https://github.com/maplibre/maplibre-react-native/releases/tag/v10.0.0-beta.6). Please try if it fixes your problem. If not, please provide a minimal reproduction repository.
