### ISSUE TITLE
Duplicate signature with Xcode 15

### ISSUE THREAD

**Issue by gorbypark** [maplibre/maplibre-react-native#237]
There seems to be an issue with some native packages and Xcode 15 (not only affecting this package).  As far as I can tell, there is no upstream fix (yet?).  Here is a [related issue](https://github.com/CocoaPods/CocoaPods/issues/12022) in the Cocoa pods repo with a fix that is specific to this project!

This is the error when using the `eas build` command, it might differ slightly if you are building with some other method. 
```
[RUN_FASTLANE] ▸ xcodebuild: error: “Mapbox.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.: The operation couldn’t be completed. File exists
```

Anyways, myself and @tylergaw on discord ended up on a temporary fix, which is a custom expo config plugin that can be enabled in a project that adds a Build Phase script that removes the offending duplicate certificate file.  It is not ideal that each project would have to install an expo config plugin, so I think this should be ported to the existing expo config plugin.

Another thing to consider is that this issue seems to affect all native projects (not just expo, or even react-native itself) so I'm unsure of the exact fix required that would handle non-expo projects.  However, I have not actually tested that this affects anything other than an expo project. Here's an [apple developer forum thread](https://forums.developer.apple.com/forums/thread/733461) filled with various examples of this affecting everything built with Xcode 15.

Anyways, I'm just creating this issue here as I'm sure others are having it, and here's the custom config plugin as a reference and if anyone out there finds it useful until a fix lands in this project / Xcode / rn / expo and etc.  Name this as `withMaplibreFix.js` and place it into something like `/plugins/withMaplibreFix.js` and add it to the plugin section of Expo's app.json

`app.json`
```js
 "plugins": [
      "./plugins/withMaplibreFix",
      ...otherPlugins,
  ]
```

`withMaplibreFix.js`
```js
const { withXcodeProject } = require('@expo/config-plugins');

const shellScript = `if [ "$XCODE_VERSION_MAJOR" = "1500" ]; then  
    echo "Remove maplibre signature file (xcode 15 workaround)"

    rm -rf "$BUILD_DIR/Release-iphoneos/Mapbox.xcframework-ios.signature"
fi`;

module.exports = function withBuildScript(config) {
  return withXcodeProject(config, async (config) => {
    const xcodeProject = config.modResults;

    xcodeProject.addBuildPhase(
      [],
      'PBXShellScriptBuildPhase',
      'Remove maplibre signature file (xcode 15 workaround)',
      null,
      {
        shellPath: '/bin/sh',
        shellScript,
      },
    );

    return config;
  });
};
```

**Comment by gorbypark** [comment]
Ahh, looks like @tylergaw has already created [PR with a proper fix](https://github.com/maplibre/maplibre-react-native/pull/238)!

**Comment by viernullvier** [comment]
FYI: This issue reappeared with `10.0.0alpha.4` because the offending signature file now has a different name. Since the update to MapLibre 6.4 renamed more instances of `Mapbox` to `MapLibre`, the config plugin should remove `MapLibre.xcframework-ios.signature` as well. Here's the patch I've set up as a quick fix for one of my repositories:

[@maplibre+maplibre-react-native+10.0.0-alpha.4.patch](https://github.com/user-attachments/files/15802606/%40maplibre%2Bmaplibre-react-native%2B10.0.0-alpha.4.patch)

**Comment by tyrauber** [comment]
Dang! @viernullvier, Nice catch!  Do we need to remove both? Or just `MapLibre.xcframework-ios.signature`?  `Mapbox.xcframework-ios.signature` shouldn't exist anymore?

**Comment by viernullvier** [comment]
@tyrauber I just tested it with a local build and confirmed your suspicion: Only `MapLibre.xcframework-ios.signature` needs to be removed, there is no `Mapbox` file anymore.

**Comment by tyrauber** [comment]
@viernullvier, thanks for the help. This should be addressed in `10.0.0-alpha.5`.

**Comment by qamarkhan1** [comment]
i'm facing issue for ios? can anyone tell me how to fix this issue
```
“MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.
Domain: NSCocoaErrorDomain
Code: 516
Failure Reason: A file with the name “MapLibre.xcframework-ios.signature” already exists.
Recovery Suggestion: To save the file, either provide a different name, or move aside or delete the existing file, and try again.

```

**Comment by talyosha** [comment]
> i'm facing issue for ios? can anyone tell me how to fix this issue
> 
> ```
> “MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.
> Domain: NSCocoaErrorDomain
> Code: 516
> Failure Reason: A file with the name “MapLibre.xcframework-ios.signature” already exists.
> Recovery Suggestion: To save the file, either provide a different name, or move aside or delete the existing file, and try again.
> ```

have you found the solution?

**Comment by tyrauber** [comment]
@talyosha, @qamarkhan1 What version of the library and what version of Xcode are you using? Is this an expo app or react-native app?  What versions? Project details would help debug this.

**Comment by qamarkhan1** [comment]
hello @tyrauber ,
i'm on react native, im facing issue when i archive but can build/run app.

"@maplibre/maplibre-react-native": "^10.1.4",
xcode version 16.1 or 16.2
im using these

**Comment by Babur171** [comment]
@tyrauber I'm also facing this issue

```
react native app
"@maplibre/maplibre-react-native": "^10.1.4",
xcode version 16.1 or 16.2
```
any proper way to fix it?

**Comment by Babur171** [comment]
@tyrauber Thank you issue is fixed, but I'm facing this issue
`MapLibre [info] Request failed due to a permanent error: Canceled  `

![Image](https://github.com/user-attachments/assets/2c6f46a7-425e-409f-9429-f31558331638)

**Comment by tyrauber** [comment]
@Babur171, just a warning. Can be ignored - [more info here](https://github.com/maplibre/maplibre-react-native/issues/368#issuecomment-2500431973). You should be good to go.
