### ISSUE TITLE
OfflinePack.pause does not pause download

### ISSUE THREAD

**Issue by timbtimbtimb** [maplibre/maplibre-react-native#265]
A progress listener will keep logging progress even after `pack.pause()` is called.

- Platform: Android
- OS version: 14.0
- Device type: Pixel_3a_API_34_extension_level_7_x86_64
- Emulator/ Simulator: yes
- Development OS: Ubuntu
- maplibre-react-native Version ^9.1.0
- React Native Version 0.73.4

Minimal reproducible example:
https://pastebin.com/Rfd2pxr1

**Comment by KiwiKilian** [comment]
This works fine on v10 pre-releases, please test with one of those.
