### ISSUE TITLE
Remove Mapbox SDK support

### ISSUE THREAD

**Issue by lseelenbinder** [maplibre/maplibre-react-native#3]
- [x] Remove the Mapbox SDK and replace it with MapLibre as the default SDK
- [x] Cleanup pass through maplibre-react-native.podspec
- [x] Set the default style to the MapLibre demo tiles
- [x] Remove references to mapbox-specific styles; looks like some enums and Android code remain, though I removed part of the iOS vestiges from ios/RCTMGL/MGLModule.m

**Comment by ianthetechie** [comment]
I have started doing this locally
