### ISSUE TITLE
Android build fails when using RN 0.74.0

### ISSUE THREAD

**Issue by csutiperec-pcu** [maplibre/maplibre-react-native#336]
### Steps to Trigger Behavior

1.  create react native project with latest (0.74.0)
2. add maplibre package
3. build for android

### Expected Behavior

App build for both Android and iOS

### Actual Behavior

App build for iOS
Build fails for Android with console error:

```
/Users/csutiperec/Git/maplibreMinimalRepro/node_modules/@maplibre/maplibre-react-native/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFunctionParser.java:6: error: DynamicFromMap is not public in com.facebook.react.bridge; cannot be accessed from outside package
import com.facebook.react.bridge.DynamicFromMap;
                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':maplibre_maplibre-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Version(s) affected

- Platform: [Android]
- Emulator/ Simulator: [Build time error]
- Development OS: [OSX 14.4.1]
- maplibre-react-native Version [^10.0.0-alpha.2]
- React Native Version [0.74.0]

**Comment by tyrauber** [comment]
Hi @csutiperec-pcu, thanks for reporting the issue.  Some research and experimentation might be necessary.

Can you try [this](https://stackoverflow.com/a/74345259).
```
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {

    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
}
```

**Comment by csutiperec-pcu** [comment]
Hi, @tyrauber! Thank you for responding. I tried the above suggestion and looked at the SO entry, adding the snippet made no noticeable difference in output.

**Comment by ghettoDdOS** [comment]
You can comment out this import line `import com.facebook.react.bridge.DynamicFromMap;` and everything will work, since this import is not used/

**Comment by csutiperec-pcu** [comment]
Removing the line fixed the build issue.

**Comment by nick42d** [comment]
Can this please be re-opened until PR #365 is meerged?

**Comment by tyrauber** [comment]
Hey @madmeatballs, I think so. 10.0.0-alpha-4 has updated MapLibre Native libraries for both Android and iOS, in addition to fixes around recent versions of Expo and ReactNative.  You'd need to patch quite a few things to make 9.1.0 work with  Expo SDK 51 / rn 0.74.1, I think.

**Comment by madmeatballs** [comment]
@tyrauber thanks, will relay this with our team. We thought alpha would be a bad idea. Although 9.1.0 is somewhat "working" in our app. 😅
