### ISSUE TITLE
Maplibre is not FOSS, Cannot publish app to F-droid

### ISSUE THREAD

**Issue by meypod** [maplibre/maplibre-react-native#34]
Hi !
I just recently wanted to publish [my app](https://github.com/meypod/al-azan) on f-droid,
[and we are facing some difficulties](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12697#note_1302177413)

can you help resolve these issues ?

I believe one of the reasons people would want to choose this package is to be FOSS and publish to f-droid

**Comment by licaon-kter** [comment]
I guess https://github.com/maplibre/maplibre-react-native/blob/main/android/rctmgl/build.gradle#L38 needs to be updated to `10` at least, since that one drops the/some non-FOSS deps

ref: https://github.com/maplibre/maplibre-gl-native/releases/tag/android-v10.0.0
