### ISSUE TITLE
Mapbox [info] Request failed due to a permanent error: Canceled 

### ISSUE THREAD

**Issue by Gabotron-ES** [maplibre/maplibre-react-native#368]
Hi everybody, on map start I get multiple warnings on my console like this: Mapbox [info] Request failed due to a permanent error: Canceled  {"level": "warning", "message": "Request failed due to a permanent error: Canceled ", "tag": "Mbgl-HttpRequest"}

How can I remove that warning? what does it mean?

**Comment by Mifayo** [comment]
@Gabotron-ES  any luck ?

**Comment by Gabotron-ES** [comment]
Nope

**Comment by tyrauber** [comment]
This is an existing issue https://github.com/maplibre/maplibre-react-native/issues/59 related to Location Permissions. More info can be found here https://github.com/rnmapbox/maps/issues/943.

**Comment by tyrauber** [comment]
@KiwiKilian, I am seeing this in alpha.27 with packages/react-native-app android.  But permissions are configured correctly in the example? Is something else going on here?

**Comment by KiwiKilian** [comment]
I've seen this for all v10. I think it's just the logger implementation, which verbosely notifies about canceled requests on a tile.
