### ISSUE TITLE
Example don't work

### ISSUE THREAD

**Issue by Anwenden001** [maplibre/maplibre-react-native#37]
The problem is that if you follow the example according to the instructions, the Error massage sequence comes up:
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

The question would be how to fix it?

ps thank you for your work

**Comment by jthiard** [comment]
On my box (ubuntu 20.04, android studio 4.2.1) the example build fine without any change.

**Comment by Anwenden001** [comment]
I use Windows 10 Education, Galaxy A51 which is based on Android 13.
I will try again later with Ubuntu.

**Comment by jthiard** [comment]
Weird indeed.
According to https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html#jvms-4.1-200-B.2 class file version 64 is Java 20.
I don't have any experience with development on windows so not sure how to investigate further.

**Comment by Anwenden001** [comment]
is fine. I think that if I find a solution I will write. thank you for your work!

**Comment by Anwenden001** [comment]
@jthiard  I have just tried to start the project manually. The error message is related to the installation of "react-native-vector-icons".
The error only appears after the installation.

**Comment by Anwenden001** [comment]
Oh now its work ok, now it works thanks for your work!

**Comment by ayubUOL** [comment]
@Anwenden001 whats the solution can you please explain !!

**Comment by Anwenden001** [comment]
I have uninstalled java, uninstalled Gradle and then deleted the Gradle folder.
After I did that, I reinstalled java and reinstalled gradle.
When installing java it is important to use the correct java version for gradle.
