### ISSUE TITLE
Unable to load sprites locally

### ISSUE THREAD

**Issue by wmonecke** [maplibre/maplibre-react-native#371]
Hey there!

I am trying to load sprites locally but I am unable to. Is there any way to do this?

Currently, I have the following in map styles.json but it seems it can't load the sprites correctly:

```json
{
  "version": 8,
  "sprite": "./sprite@2x.png",
  ... etc
```

**Comment by tyrauber** [comment]
@wmonecke, I don't think you can use a relative path in styles.json like that. What would the path be relative to?  Is styles.json hosted on a server? Are the assets remote as well?

If you are including the sprites in the app bundle, then I think the better approach would be to construct your style as JSON and pass it to MapView as the `styleJSON` property. Then you could use `path.resolve(__dirname, "./sprite@2x.png")` to resolve the path to the sprite asset in the bundle.

**Comment by wmonecke** [comment]
@tyrauber Hey there! Thank you for your help. I am a bit confused though. I can't use `path.resolve(__dirname, "./sprite@2x.png")` inside react-native. Where exactly would you call this?

**Comment by tyrauber** [comment]
Sure, you can! You can also use also use typescript or babel path aliases to resolve a relative path. 

The point is if you want to load a sprite that is included in your bundle you should construct your map style as a json object and pass it to MapView styleJSON. In that json, you can have a relative path to the sprite, but it needs to resolve correctly to the file location in your app bundle.

**Comment by KiwiKilian** [comment]
Would also say `path.resolve` wouldn't work. Maybe using `require` on the sprite in a style defined with in your JS/TS could work. Did you ever figure this out @wmonecke?

**Comment by wmonecke** [comment]
I ended up pointing to ArcGIS directly, instead to my local sprites

// styles.json
```javascript
{
  "version": 8,
   "sprite": "https://www.arcgis.com/sharing/rest/content/items/[blah]/resources/sprites/sprite-1689370895283?token={token}",
   ...
```

then did a `.replace()` for `{token}` with the right env token.
