### ISSUE TITLE
Navigation Library Support?

### ISSUE THREAD

**Issue by acollazomayer** [maplibre/maplibre-react-native#39]
Does the package support the navigation library?

**Comment by ianthetechie** [comment]
Not directly. PRs welcome, but the state of the MapLibre Navigation SDKs is in flux right now.

The iOS and Android SDKs are forked from very different Mapbox SDKs, which were themselves already diverging from each other.

iOS had a navigation UI, but it has some issues with [the camera](https://github.com/maplibre/maplibre-navigation-ios/issues/1) and [doesn't really support non-Mapbox styles](https://github.com/maplibre/maplibre-react-native/issues/39) so it's hardly usable for most applications in my opinion.

Android until very recently had ripped out the navigation UI, which makes it basically unusable for most applications (that's kind of the point of an SDK). However, v2.0 appears to have fixed this.

Sorry that was a rather roundabout way to say "no", but I would not expect the React Native SDK to get support until the native SDKs are ready for wider use on both platforms.

**Comment by acollazomayer** [comment]
@ianthetechie Thanks for the information. Do you know of a library that can support navigation for react-native?

**Comment by ianthetechie** [comment]
@acollazomayer With the disclaimer that I have not tried this and have no clue how well it would work, you could try checking this out: https://github.com/mslabenyak/react-native-mapbox-navigation.

Known caveats:

* It uses an *ancient* Mapbox navigation SDK. This is from before they changed the license, it would appear, but it's going to be quite old and still uses OpenGL (somewhat of a ticking time bomb). It hasn't been touched in years.
* You haven't said what vendor you're using for the routes, but this SDK assumes you're using Mapbox. It is possible, though not well documented, to use another vendor with a Mapbox navigation SDK as long as the other vendor has an OSRM-compatible response and you are OK writing some glue code to make requests and convert the responses to a Mapbox-consumable format yourself. If this is something you're interested in (despite the non-trivial caveats), we have some experience helping clients do this at Stadia Maps with our APIs .
