### ISSUE TITLE
iOS 17.5.x crashing

### ISSUE THREAD

**Issue by ngdbao** [maplibre/maplibre-react-native#402]
Hi, 

Since iOS 17.5.0, Crash Analytics reports few cases to me.
From statistic, all crashing come from only iPhone XS Max and iOS >= 17.5.0
I wish I could have minimal reproduce, but these Stack trace may help hopefully.

[issue_8a3647f99fc8a4a47c8174d15810f0b7_crash_session_c53ee078483846f192a38ceff981c1e9_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/15542794/issue_8a3647f99fc8a4a47c8174d15810f0b7_crash_session_c53ee078483846f192a38ceff981c1e9_DNE_0_v2_stacktrace.txt)
[issue_8a3647f99fc8a4a47c8174d15810f0b7_crash_session_d31463c1fbea48738bcd38ea16fbd264_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/15542797/issue_8a3647f99fc8a4a47c8174d15810f0b7_crash_session_d31463c1fbea48738bcd38ea16fbd264_DNE_0_v2_stacktrace.txt)

**Comment by tyrauber** [comment]
@ngdbao, is this 9.1.0 or 10.0.4.alpha?  If 9.x, then 10.0.4 may resolve the issue (as it uses the latest Maplibre native libraries).

**Comment by ngdbao** [comment]
> @ngdbao, is this 9.1.0 or 10.0.4.alpha? If 9.x, then 10.0.4 may resolve the issue (as it uses the latest Maplibre native libraries).

It's 9.1.0 indeed

I'll give a try on 10.0.0-alpha.4
Thanks

**Comment by mwmcode** [comment]
Hi @tyrauber 
I'm having issues upgrading to alpha 10.0.4. 
"Failed to resolve dependencies Dependencies could not be resolved because root depends on 'maplibre-gl-native-distribution' 5.13.0 and root depends on 'maplibre-gl-native-distribution' 6.4.0."

```sh
error Failed to build ios project. "xcodebuild" exited with error code '74'. To debug build logs further, consider building your app with Xcode.app, by opening 'eTA.xcworkspace'.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace eTA.xcworkspace -configuration Debug -scheme eTA -destination id=185ED13D-572C-4753-A358-279397A1147B

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph


Resolved source packages:
  MapLibre GL Native: https://github.com/maplibre/maplibre-gl-native-distribution @ 5.13.0
```

**Comment by lmeier** [comment]
Confirmed that upgrading to `10.0.0-alpha.4` fixed this issue for me.

Any idea when we'll get a full release for `10.0.0`? I maintain a package that takes a peer dependency on this and I'd prefer to not be pointing to an alpha.
