### ISSUE TITLE
Symbol Layer Icon Color

### ISSUE THREAD

**Issue by danish-danial** [maplibre/maplibre-react-native#406]
Hey everyone,

I can't seem to change the color of the `Symbol Layer` icon. I refer to the [StackOverflow](https://stackoverflow.com/questions/63299999/how-can-i-create-sdf-icons-used-in-mapbox-from-png) on how to convert the icon and etc. It seem the icon still white even though I assign the `iconColor` in style.

Here are the line of the code:
```JS
 <SymbolLayer
                    key={index}
                    id={`vector-layer-${index}`}
                    style={{
                      iconImage: pointMarker,
                      iconSize: 0.05,
                      iconOpacity: vector.hidden ? 0 : 1,
                      iconColor: vector.color,
                    }}
/>
```

![image](https://github.com/maplibre/maplibre-react-native/assets/2580444/a1353914-d7ce-4f76-8796-d0e735b4c046)

Can you give me a guidance on how can I color the `Symbol Layer`?

Thanks.

**Comment by caspg** [comment]
Is your `icon` in `SDF` format?
