### ISSUE TITLE
[Expo web] requireNativeComponent is not a function

### ISSUE THREAD

**Issue by timbtimbtimb** [maplibre/maplibre-react-native#414]
Hello

I am trying to run the most bare bones app with `npx create-expo-app@latest` and `expo install @maplibre/maplibre-react-native` but once I run `npm run web` I get the following error

```
Metro error: (0 , _index.requireNativeComponent) is not a function

  619 | );
  620 |
> 621 | const RCTMLNCamera = requireNativeComponent<NativeProps>(NATIVE_MODULE_NAME);
      |                                            ^
  622 |
  623 | export default Camera;
  624 |
```

Here is a [Git repository](https://github.com/timbtimbtimb/reactnative-maplibre-web-bug) for you to try it out

Thank you very much

**Comment by tyrauber** [comment]
@timbtimbtimb, I don't think this library can work with expo web, as it requires ios and android native libraries.

Your best bet is to use a react-native Platform conditional, `Platform.OS === 'web'`, and use the MapLibre JS library for web.
