### ISSUE TITLE
Typescript compilation errors in HeadingIndicator and geoUtils v10.0.0-alpha.9

### ISSUE THREAD

**Issue by madmeatballs** [maplibre/maplibre-react-native#422]
### Steps to Trigger Behavior

1. install @maplibre/maplibre-react-native 10.0.0-alpha.9 to your project
2. npx tsx --noEmit

### Expected Behavior

no ts issues

### Actual Behavior

ts errors in both `javascript/components/HeadingIndicator.tsx:4:25` and `javascript/utils/geoUtils.ts:2:25`

### Screenshots (if applicable)
![Screenshot 2024-07-16 at 3 39 02 PM](https://github.com/user-attachments/assets/15ddd296-effe-4e32-b8c7-23db10e0e083)

### Version(s) affected

- maplibre-react-native Version 10.0.0-alpha.9

**Comment by madmeatballs** [comment]
https://github.com/maplibre/maplibre-react-native/issues/416

**Comment by veno501** [comment]
these can be suppressed by writing your own .d.ts file and declaring `module ‘*.png’` and `module ‘@mapbox/geo-viewport’`

**Comment by caspg** [comment]
Hey, thanks for reporting the issue. 

When I run `yarn run typescript:check` (alias for `tsc -p ./tsconfig.json --noEmit`) inside the `maplibre-react-native` repo I don't have any TS errors.
Can you share your tsconfig file?

**Comment by caspg** [comment]
@veno501 and you have the same TS errors as in the original message?

**Comment by caspg** [comment]
Okey, it looks that when add this package to our projects, [custom types](https://github.com/maplibre/maplibre-react-native/tree/main/javascript/%40types) are excluded. We could explicitly include them in project's tsconfig but there must be some better way 🤔

**Comment by madmeatballs** [comment]
Here is our tsconfig.

```{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "paths": {
      "@xxx/*": ["./*"],
      "@env": ["./config/env.js"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"]
}
```
