### ISSUE TITLE
Maplibre "9.1.0" Android build issue: DynamicFromMap 

### ISSUE THREAD

**Issue by MufeedaFi** [maplibre/maplibre-react-native#425]
I have been using "@maplibre/maplibre-react-native": "9.1.0"  in my React native project with "react-native": "0.74.2", which builds and works fine for iOS. 

But, while I run in android, the library is giving build failure with below error

> @maplibre/maplibre-react-native/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFunctionParser.java:6: error: DynamicFromMap is not public in com.facebook.react.bridge; cannot be accessed from outside package
> import com.facebook.react.bridge.DynamicFromMap;

Has anyone encountered this issue?

**Comment by daamsie** [comment]
Yes, I also just encountered this. react-native 0.74.3 and maplibre-react-native 9.1.0

**Comment by MufeedaFi** [comment]
yup. The solution is to patch the library by commenting `import com.facebook.react.bridge.DynamicFromMap;`
You can refer this: https://github.com/maplibre/maplibre-react-native/issues/336

**Comment by daamsie** [comment]
Ah sorry for the overlap - just found the same issue

**Comment by MufeedaFi** [comment]
Fixed
