### ISSUE TITLE
Warning: MarkerView: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. 

### ISSUE THREAD

**Issue by Pieeer1** [maplibre/maplibre-react-native#430]
### Steps to Trigger Behavior

1. Create a new MapLibreGL.MapView
2.. Add a MarkerView with coordinates
3. Build and run the application. you will receive the warning.

### Link to Minimal Reproducible Example
```
        <View style={styles.container}>
         <MapLibreGL.MapView
            ref={mapRef}
            style={styles.map} 
            logoEnabled={false} 
            styleURL={mapUri + token}
            rotateEnabled={false}
            zoomEnabled={true}
         >
            <MapLibreGL.Camera
            zoomLevel={2}
            centerCoordinate={[defaultView?.longitude ?? 0, defaultView?.latitude ?? 0]}
            />
            { shipment?.shipmentStops.map((x, i) => {
            return (
                <MarkerView key={i} coordinate={[x.location?.longitude ?? 0, x.location?.latitude ?? 0]}>
                    <View style={{backgroundColor: 'red', width: 10, height: 10, borderRadius: 5}}></View>
                </MarkerView>
                )
            })}

            <RippleButton iconName="mode-of-travel" iconSize={25} onPress={() => setIsLiveView(!isLiveView)} color="#000000" ></RippleButton>
         </MapLibreGL.MapView>
        </View>
```
### Expected Behavior
No Warning
### Actual Behavior
Warning
### Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/9be2f0b3-5e7e-4369-9c13-ceec1f41423e)

### Version(s) affected

- Platform: [e.g. Android, iOS]
- OS version: [e.g. Android 9, iOS 10]
- Device type: [e.g. iPhone6]
- Emulator/ Simulator: [yes/ no]
- Development OS: [e.g. OSX 11.0.1, Win10]
- maplibre-react-native Version [e.g. 7.0.9]
- MapLibre GL version [e.g. 6.3.0]
- React Native Version [e.g. 0.59]

**Comment by RobertSasak** [comment]
## Observations
React it deprecating defaultProps in function component. https://github.com/facebook/react/pull/25699
https://github.com/facebook/react/blob/main/CHANGELOG.md#1830-april-25-2024

MarkerView is such a component https://github.com/maplibre/maplibre-react-native/blob/9fcf6d162b49044a3789eadc5c1d4b784444728d/javascript/components/MarkerView.tsx#L56
