### ISSUE TITLE
Map boundaries do not restrict view as expected 

### ISSUE THREAD

**Issue by Rutvik-tbz** [maplibre/maplibre-react-native#432]
Steps to Trigger Behavior
Set boundaries on the MapLibre map using the maplibre-react-native library.
Pan or zoom the map to the edge of the defined boundaries.
Observe the behavior when reaching the boundary limits.

Expected Behavior
The map should restrict the view to stay within the defined boundaries, preventing the user from panning or zooming outside these limits.

Actual Behavior
The map allows panning or zooming outside of the set boundaries a little after that it restricts and if I zoom it certain level then it will set me in the actual boundary, displaying areas that the boundary settings should restrict.

zoom level: 13.65
minZoomLevel: 13.5

![shared image](https://github.com/user-attachments/assets/4bc27b47-349a-4d9f-8815-dea8a2500d77)
in this, I can scroll outside my boundary 

Additional Context
I am using the maplibre-react-native library to set map boundaries, but I noticed that the map does not restrict the view as expected. Instead, it allows the user to view areas outside the defined boundaries. This issue occurs even though I have set the boundaries according to the library's documentation. I'm looking for guidance or a fix for this behaviour.

**Comment by KiwiKilian** [comment]
Bounds are working as expected in the `RestrictBounds` examples in this repository. It limits the center of the map to be within the bounds defined in the `maxBounds` prop of the `Camera`.  For example in this screenshot it's not possible to pan further down or to the left:

![Image](https://github.com/user-attachments/assets/f3ef7ff2-b1b8-4694-ac7c-7cb0ba8f2bfd)

If you still think there is a bug, please provide a complete reproduction.
