### ISSUE TITLE
Lines hidden when belowLayerID is setted with "com.mapbox.annotations.points"  (Android)

### ISSUE THREAD

**Issue by flohhhh** [maplibre/maplibre-react-native#448]
Hello,

I upgraded from version `10.0.0-alpha.5` to `10.0.0-alpha.13`, and since this update, I no longer see the lines on Android when I set the belowLayerID property to 'com.mapbox.annotations.points'. If I remove it, I can see the lines, but they appear above my PointAnnotations.

I’m wondering if the value `com.mapbox.annotations.points` has changed between these versions. If not, is there another solution to display the PointAnnotations above the lines?

Thanks a lot.

My code:

```
<MapLibreGL.ShapeSource
      id={`shape-source-${idIndex}`}
      lineMetrics
      shape={shape}
    >
      <MapLibreGL.LineLayer
        id={`line-layer-${idIndex}`}
        style={styles.lineLayer}
        belowLayerID={isAndroid ? 'com.mapbox.annotations.points' : undefined}
      />
</MapLibreGL.ShapeSource>
```

- Platform: Android
- maplibre-react-native 10.0.0-alpha.13
- React Native Version 0.74.5
- Expo 51.0.32

**Comment by tyrauber** [comment]
@flohhhh, I am trying to think what could have changed between alpha.5 and 13 that would cause this. We updated the Maplibre Android and iOS SDKs, and there was a class name change from mapbox to maplibre. I am wondering if maybe that could be the issue. Can you try `com.maplibre.annotations.points` and report back? 

You could also try inspecting the layers using [map.queryRenderedFeaturesAtPoint(point)](https://github.com/maplibre/maplibre-react-native/blob/main/docs/MapView.md#queryrenderedfeaturesatpointpoint-filter-layerids), to confirm the layer order.

**Comment by flohhhh** [comment]
@tyrauber thx for the indications. I didn't succeed with `com.maplibre.annotations.points` but I searched in the native maplibre code and here is the [culprit](https://github.com/maplibre/maplibre-native/blob/77a464d3355a65b54972b2ade48a8e80d7df049b/platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/constants/MapLibreConstants.java#L200). 

With this value it works : `org.maplibre.annotations.points` :)
