### ISSUE TITLE
XCode 16 archive upload issues with alpha.17

### ISSUE THREAD

**Issue by madmeatballs** [maplibre/maplibre-react-native#456]
### Steps to Trigger Behavior

1. Archive your project for iOS
2. Notice that issues appears when uploading app to App Store Connect

### Minimal Reproducible Example
install alpha.17 version, archive project, and upload to app store connect

### Expected Behavior
no issues should appear when uploading to app store connect

### Actual Behavior
refer to screenshot

### Screenshots (if applicable)
![Screenshot 2024-09-19 at 9 53 06 AM](https://github.com/user-attachments/assets/d3594c64-fffa-4d79-ae07-90ab7cfe2e7b)

### Version(s) affected

- Platform: iOS
- Development OS: MacOS 15.0
- maplibre-react-native Version 10.0.0-alpha.17
- React Native Version 0.74.3
- XCode 16

**Comment by tyrauber** [comment]
Thanks @madmeatballs, Are these just warnings, or are you actually prevented from submitting? Unfortunately this seems to be a new issue Xcode 16. See: [763731](https://forums.developer.apple.com/forums/thread/763731), [764445](https://forums.developer.apple.com/forums/thread/764445).

**Comment by madmeatballs** [comment]
> Thanks @madmeatballs, Are these just warnings, or are you actually prevented from submitting? Unfortunately this seems to be a new issue Xcode 16. See: [763731](https://forums.developer.apple.com/forums/thread/763731), [764445](https://forums.developer.apple.com/forums/thread/764445).

I think these are just issue warnings, I am able to upload it and publish anyway.
