### ISSUE TITLE
Maplibre.Offlinemanager is not working properly

### ISSUE THREAD

**Issue by HarshaZeitview** [maplibre/maplibre-react-native#462]
Hello,

We found a a bug?, when we tried to use MapLibreGL.offlineManager.createPack function with Maplibre 10

so the below code is not working properly, when bounds is provided, the download has been stoped at 30% after again we retry it, starts from 30% upto 60% again it has been failed and again if we retry it starts from 60% to 100% or again it stops in between.

```
const saveOfflineMaps = (bounds, offlinePackName) => {
  return new Promise(async (resolve, reject) => {
    try {
      const progressListener = async (_, status) => {
        if (status.percentage === 100) {
          if (status.requiredResourceCount === status.completedResourceCount) {
            resolve("success");
          } else if (
            status.requiredResourceCount === status.erroredResourceCount
          ) {
            await MapLibreGL.offlineManager.deletePack(offlinePackName);
            reject("failure");
          }
        }
      };

      const errorListener = async (_, err) => {
        await MapLibreGL.offlineManager.deletePack(offlinePackName);
        reject(err);
      };

      await MapLibreGL.offlineManager.createPack(
        {
          name: offlinePackName,
          styleURL: `https://tiles.stadiamaps.com/styles/alidade_satellite.json?api_key=${Config.STADIA_MAP_API_KEY}`,
          minZoom: 14,
          maxZoom: 23,
          bounds: [
            [bounds[0], bounds[1]],
            [bounds[2], bounds[3]],
          ],
        },
        progressListener,
        errorListener,
      );
    } catch (error) {
      await MapLibreGL.offlineManager.deletePack(offlinePackName);
      reject(error);
    }
  });
};
```

so when we try to save the pack for offline use, it should complete total 100% in one go, or it should failure.
**This is only happing with Maplibre but working fine with MapboxGl** (i.e rnmapbox/maps)

**Comment by KiwiKilian** [comment]
What's the error received by the `errorListener`?

**Comment by HarshaZeitview** [comment]
Hi @KiwiKilian 

so we are getting this Error
```
message: "Error Domain=MLNErrorDomain Code=3 "
name: "pack_name"
```
and the percentage is downloaded upto 35%. you can see the log below one,
```
completedResourceCount: 524
completedResourceSize: 16432790
completedTileCount: 6
completedTileSize: 542418
name: "e110c554-12fe-45e2-ab7e-8e2fd5d22e9d-84baf6a7-49ec-4745-a993-15753083d71a"
percentage: 35
requiredResourceCount: 1540
state: 2
```

so it's happening frequently so if we retry again & again upto 3 to 5 times and then it starts from the 35 % and again it is stopping at around 60% or some X% and again if we retry it goes to 100% and then saved successfully.

so could you please check it and let us know why this is happening @KiwiKilian thanks!.

**Comment by KiwiKilian** [comment]
Which version are you using?

**Comment by HarshaZeitview** [comment]
Hi @KiwiKilian we are using this one - **"@maplibre/maplibre-react-native": "10.0.0-alpha.25"**

**Comment by KiwiKilian** [comment]
It's hard to tell, what the actual problem is, the error seems incomplete. Check if there is more info on the error like doing `console.log(JSON.stringify(error)`. For me the `OfflineManager` is working fine with a vector source, can't tell about Stadia and or raster sources.

**Comment by HarshaZeitview** [comment]
Hi @KiwiKilian 
it is happening on both the platforms and not working for larger area i guess because it is working fine with smaller area.
so could you try with this **below object for creating pack**,
```
{
          name: "pack_name",
          styleURL: `https://tiles.stadiamaps.com/styles/alidade_satellite.json`,
          minZoom: 14,
          maxZoom: 23,
          bounds: [
            [-119.04118040004413, 35.81589526155756],
            [-119.0359232703748, 35.82402341448827],
          ],
}
```

so @KiwiKilian this is the error message we have got it,
`{"message":"Error Domain=MLNErrorDomain Code=3 \"The request timed out.\" UserInfo={NSLocalizedFailureReason=The request timed out.}","name":"e110c554-12fe-45e2-ab7e-8e2fd5d22e9d-84baf6a7-49ec-4745-a993-15753083d71a"}`

and @KiwiKilian i am getting this warning when we clear the data i.e **resetDatabase**
```
MapLibre warning [event]:Database [code]:-1 [message]:Removing existing incompatible offline database 
filePath: "virtual bool mbgl::MLNCoreLoggingObserver::onRecord(EventSeverity, Event, int64_t, const std::string &)"
level: "warning"
line: 27
message: "[event]:Database [code]:-1 [message]:Removing existing incompatible offline database"
```
so if we reset the database **it is not actually deleting all the packs**.

**Comment by KiwiKilian** [comment]
The important part is:

> The request timed out.

This is either a network problem or you are [exceeding the offline limits of Stadia (no more than 100mb!)](https://stadiamaps.com/terms-of-service).

The second one is simply a [warning from MapLibre Native](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/src/mbgl/storage/offline_database.cpp#L149), that the DB is loading.

Both of these problems aren't connected to this project.

**Comment by HarshaZeitview** [comment]
Hi @KiwiKilian okay let us assume that i have a **network problem** or **exceeding the offline limits of Stadia (no more than 100mb!**

but how it is working with this library with same input -> https://github.com/rnmapbox/maps/blob/main/docs/OfflineManager.md 

and regarding the second issue, when we use this below line only we are getting that warning and not clearing the offline database.
`await MapLibreGL.offlineManager.resetDatabase();`
so it is linked with this project only right ? as MapLibreGL is imported from this one
**import MapLibreGL from '@maplibre/maplibre-react-native';**

so  @KiwiKilian when i use the **resetDatabase** it should delete all my offline packs, but it is not deleting it i need to uninstall the app to delete all the downloaded packs.

**Comment by KiwiKilian** [comment]
RNMapbox and MapLibre React Native divereged quite a bit already. Also the downloading is mostly part of the native SDKs, this Library only is wrapper towards the native SDKs. The error reason "Request timed out" just points completely out of the bounds of this repo.

Regarding `resetDatabase()`, how do you determine the packs are not deleted? I just tested on an Android and iOS device:

1. Downloaded ~1 GB of Vector Tiles.
1. Check the size the documents of the app take (Android long press app icon "Info", iOS settings "Storage")
1. Run `await MapLibreGL.offlineManager.resetDatabase();`
1. Storage needed by documents decreased drastically

I'am seeing the same warning, it's just implemented that way in the native SDK.
