### ISSUE TITLE
Typescript compilation errors in HeadingIndicator and geoUtils v10.0.0-alpha.22

### ISSUE THREAD

**Issue by madmeatballs** [maplibre/maplibre-react-native#476]
### Steps to Trigger Behavior

1. install @maplibre/maplibre-react-native 10.0.0-alpha.22 to your project
2. npx tsc --noEmit

### Expected Behavior

no ts issues

### Actual Behavior

ts errors in `javascript/components/HeadingIndicator.tsx:4:25`

### Screenshots (if applicable)
![Screenshot 2024-10-24 at 6 05 03 PM](https://github.com/user-attachments/assets/903fcd3c-049c-4add-8b2e-91f18286da0c)

### Version(s) affected

- maplibre-react-native Version 10.0.0-alpha.22

**Comment by madmeatballs** [comment]
https://github.com/maplibre/maplibre-react-native/issues/422

seems like this issue has come back. Now just the heading.png

**Comment by madmeatballs** [comment]
@tyrauber the fix seems to be the same fix as before in https://github.com/maplibre/maplibre-react-native/pull/423/files by @caspg

**Comment by KiwiKilian** [comment]
Sorry, I might have reintroduced the problem. But there should be a better solution than `@ts-ignore`. Will have a look tomorrow. What does your `tsconfig.json` look like?

**Comment by KiwiKilian** [comment]
Ok, I can reproduce the problems about the `*.png` types, but are you sure there is also a problem again around the geoUtils?

**Comment by KiwiKilian** [comment]
This was fixed and will be further improved through fixing #482.
