### ISSUE TITLE
RFC: Deprecate/Remove `Style` component and unify `MapView`s prop `styleURL` and `styleJSON`

### ISSUE THREAD

**Issue by KiwiKilian** [maplibre/maplibre-react-native#512]
Working through the examples, I noticed for the first time the [`Style` component](https://github.com/maplibre/maplibre-react-native/blob/main/javascript/components/Style.tsx). The component basically allows to read a `style.json` and it will create `Source` and `Layer` components, to render the style partially.

This is confusing, because it's also possible to pass a JSON style via `styleJSON` on `MapView`, so this functionality is duplicated. It turns out, initially there was no support for local JSON styles at all. Then the `Style` component was [introduced](https://github.com/rnmapbox/maps/issues/846), before finally `MapView` got support for also `styleJSON`. The author of both did also recommend to keep only the [functionality on `MapView` through `styleJSON`](https://github.com/rnmapbox/maps/pull/1102#issuecomment-735968413), but that component seemed to got forgotten.

I would like to do the following:

- Deprecate/Remove `Style` component
  - Removes duplicate funcitonality and confusion about which to use
  - If someone wants to render a style, but not as the `MapView` `styleJSON`, this is a user space concern, nothing this library has to solve
  - It will help keep us this library clean in functionality
- Unify `styleURL` and `styleJSON` to a new prop `mapStyle`, just like [`react-map-gl` uses](https://visgl.github.io/react-map-gl/docs/api-reference/map#mapstyle), `mapStyle` should then accept either a URL or a Style object

Smoothest migration would be first to deprecate `Style` and `MapView`s `styleURL` and `styleJSON` for one major version and then drop on the next major version. Immediate removal would be less work.

**Comment by cashc** [comment]
I'd vote for removing it now. Seems to me like a straightforward change that is a cleaner approach and breaking changes like these can be expected with a major version release.
I imagine that would mean you'd want to add some sort of 10.0 migration documentation to the readme that outlines the fact the if you're using the `Style` component currently, you'll have to switch to using `MapView mapStyle=...` approach.

Just my two cents (: Thank you for your work!

**Comment by KiwiKilian** [comment]
@cashc thanks for your comment! I'm with you on immediate removal of the `Style` component, my guess is, there are very few users of it.

The migration towards `mapStyle` from `styleJSON` and `styleURL` will affect everyone. So maybe deprecate those two props for one major version and remove them in the next major version?

A migration doc should be a must, you are right!

**Comment by tyrauber** [comment]
I agree with htis.  `styleJSON` and `styleURL` is more explicit.  Having a prop that takes a url or json is not.  I am fine with the breaking change as long as the docs are updated.

**Comment by KiwiKilian** [comment]
Are you also fine with removing the `Style` component?

**Comment by tyrauber** [comment]
If it is not needed. Reviewing [the style component ](https://github.com/maplibre/maplibre-react-native/blob/main/src/components/Style.tsx#L305-L309)it looks like it is responsible for parsing the JSON and adding it to the map based on the style spec.  Does `styleJSON` handle this differently?
