### ISSUE TITLE
Enabling `followUserLocation` with other `follow` props on `Camera` is non-deterministic

### ISSUE THREAD

**Issue by KiwiKilian** [maplibre/maplibre-react-native#530]
The `followUserLocation` and other `follow` props of the `Camera` are currently non-deterministic and don't work as expected.

Reproduction is possible with the following example. It basically switches between normal map browsing into a "navigation mode", by following the user and applying pitch:

```tsx
import MapLibreGL, {
  UserLocationRenderMode,
  UserTrackingMode,
} from "@maplibre/maplibre-react-native";
import { useState } from "react";
import { Button } from "react-native";

import maplibreIcon from "../../assets/images/maplibre.png";
import { OSM_RASTER_STYLE } from "../../constants/OSM_RASTER_STYLE";
import { sheet } from "../../styles/sheet";

export default function UserLocationForNavigation() {
  const [navigationActive, setNavigationActive] = useState(false);

  return (
    <>
      <Button
        title={`Navigation is ${navigationActive ? "active" : "inactive"}`}
        onPress={() => setNavigationActive((prevState) => !prevState)}
      />

      <MapLibreGL.MapView
        style={sheet.matchParent}
        styleJSON={JSON.stringify(OSM_RASTER_STYLE)}
        contentInset={navigationActive ? [200, 0, 0, 0] : undefined}
        // pitchEnabled={navigationActive}
      >
        {navigationActive ? (
          <MapLibreGL.UserLocation
            renderMode={
              navigationActive
                ? UserLocationRenderMode.Normal
                : UserLocationRenderMode.Native
            }
            showsUserHeadingIndicator
          >
            <MapLibreGL.SymbolLayer
              id="navigation-icon"
              style={{
                iconImage: maplibreIcon,
                iconPitchAlignment: "map",
                iconAllowOverlap: true,
              }}
            />
          </MapLibreGL.UserLocation>
        ) : null}

        <MapLibreGL.Camera
          followUserLocation={navigationActive}
          followUserMode={
            navigationActive
              ? UserTrackingMode.FollowWithHeading
              : UserTrackingMode.Follow
          }
          followZoomLevel={19}
          followPitch={navigationActive ? 60 : 0}
          onUserTrackingModeChange={(event) => {
            console.log(event.nativeEvent.payload);

            if (
              navigationActive &&
              !event.nativeEvent.payload.followUserLocation
            ) {
              setNavigationActive(false);
            }
          }}
        />
      </MapLibreGL.MapView>
    </>
  );
}
```

Expected behavior on both platforms when enabling navigation for the first and following times:
- Zoom to user location
- Change pitch
- Follow user location with said pitch

| Android  | iOS |
| ------------- | ------------- |
 | <video src="https://github.com/user-attachments/assets/c8475610-a6fc-4027-9481-2096677f5222" /> | <video src="https://github.com/user-attachments/assets/e17b27f3-1f44-4764-b729-668f7e0fb204" /> |

I suspect the migration to function components to be still faulty for the `Camera` component. Lets [review the code](https://github.com/maplibre/maplibre-react-native/blob/31bdad0c4986c84a990f73e1a0dd6fbf5b7b6be2/javascript/components/Camera.tsx) at the latest point before migration to FC.

The component was never re-rendered, the props were only initially passed via `render` for the first ever render cycle. Afterwards it was blocked by:

https://github.com/maplibre/maplibre-react-native/blob/31bdad0c4986c84a990f73e1a0dd6fbf5b7b6be2/javascript/components/Camera.tsx#L212-L214

This is the `render` method which initially passes the native props:

https://github.com/maplibre/maplibre-react-native/blob/31bdad0c4986c84a990f73e1a0dd6fbf5b7b6be2/javascript/components/Camera.tsx#L651-L676

Now looking into how the props were updated within the Class Component we see this `UNSAFE_componentWillReceiveProps`. It was the reason, why the migration was done as this is deprecated.

https://github.com/maplibre/maplibre-react-native/blob/31bdad0c4986c84a990f73e1a0dd6fbf5b7b6be2/javascript/components/Camera.tsx#L208-L210

And this called the `_handleCameraChange` function:

https://github.com/maplibre/maplibre-react-native/blob/31bdad0c4986c84a990f73e1a0dd6fbf5b7b6be2/javascript/components/Camera.tsx#L216-L304

This one calls `setNativeProps` in specific order. E.g. it sets `followUserLocation` first, then other `follow` props and only then restrictions/controlled camera position. This might be the culprit for the now rather unclear behavior. It looks like it's native props are updated in a random order, when just rendering the `NativeComponent` and passing the props.

To be honest I'm not 100 % sure how to fix this. I couldn't find any docs around native props order during updating. I have some ideas:

- Try to match the behavior of the old Class Component with the Functional Component
  - I would guess this means running through `useEffect` and maybe storing old props within a `ref`
  - Is this the approach you tried here @caspg? https://github.com/maplibre/maplibre-react-native/blob/a45fc558cd49cc28ced40a572851be7136419359/javascript/components/Camera.tsx#L383-L391
  - Maybe we have to take the best of both worlds, my refactoring and your `useEffects` but without the `NativeComponent` getting the props passed?
- Batching Native Props (like putting it into one object?)
  - Could create even more problems
  - Especially when there are partial updates
- How does this change when migrating to the new architecture?

**Comment by caspg** [comment]
I was trying what was done in class component but I didn't suspect that order of passing native props matter. It's quite strange 🤔
