### ISSUE TITLE
Cannot import RegionPayload type for MapView onRegionWillChange handler with TypeScript

### ISSUE THREAD

**Issue by EmilJunker** [maplibre/maplibre-react-native#534]
### Steps to Trigger Behavior

1. Try to import the `RegionPayload` type declared here and use it in your code. https://github.com/maplibre/maplibre-react-native/blob/ea8513019ae97f7b5271d7d2cda7b288a5021114/src/components/MapView.tsx#L50-L59
2. Notice that it's not possible :(

### Minimal Reproducible Example

For example, try to declare a handler function for the `onRegionWillChange` prop of the `MapView` component with TypeScript:

![Image](https://github.com/user-attachments/assets/ae8a8e7d-4fb8-41cd-8fc3-4d5f332f3375)

```ts
const regionWillChangeHandler = (feature: GeoJSON.Feature<GeoJSON.Point, RegionPayload>) => {
    console.log(feature);
};
```

### Expected Behavior

I would expect to be able to do import the `RegionPayload` type, e.g. like this:

```ts
import { RegionPayload } from '@maplibre/maplibre-react-native';
```

### Actual Behavior

I get this error:

```
Module '"@maplibre/maplibre-react-native"' has no exported member 'RegionPayload'.
```

### Environment

- Development OS: Windows 11
- `@maplibre/maplibre-react-native` Version: 10.0.0-beta.1
- `react-native` Version: 0.76.1

### Additional Context

In version `10.0.0-alpha.23`, I was still able to import the `RegionPayload` type as follows. Although this was not ideal, at least it worked:

```ts
import { RegionPayload } from '@maplibre/maplibre-react-native/javascript/components/MapView';
```

**Comment by KiwiKilian** [comment]
Thanks for the report, there are few types like this, which we should be exporting properly. It has been previously possible unofficially, which is not restricted through the build process.

**Comment by brentforder** [comment]
It is possible to import it... It's just not importable from the library root.
`import { RegionPayload } from '@maplibre/maplibre-react-native/src/components/MapView';`

I also have to do a funky import for MapLibreRNEvent for the parameter of the Camera.onTrackingModeChange().
`import { MapLibreRNEvent } from '@maplibre/maplibre-react-native/src/types/MapLibreRNEvent';`
