### ISSUE TITLE
MapLibreGL.Animated.ImageSource not work if the device is totally offline

### ISSUE THREAD

**Issue by babeone** [maplibre/maplibre-react-native#54]
I am currently attempting to utilize this library in an entirely offline capacity; however, I am encountering issues with the ImageSource, as it is not successfully rendering the image.

The project I am working on is an offline application, and I do not anticipate having an internet connection available, i need to display a custom map Image with some CircleLayer and text inside, i'm using this library because i can geoReference the custom map Image in the real world with coordinations, but  it seems  ImageSource don't support offline imported Image. I don't need tiles or streets, just the CustomImage placed in the real world with coords.

I'm developing on an Android physical device (Pixel 7), not tried IOS, i'm waiting the device

this is an example of the code:

```jsx
import MapLibreGL from "@maplibre/maplibre-react-native";
import mapImage1 from "./map/1.png";

const styleJson = require("./map/style.json");

MapLibreGL.setAccessToken(null);

function App(): JSX.Element {
  return (
    <MapLibreGL.MapView
      style={styles.map}
      logoEnabled={false}
      styleJSON={JSON.stringify(styleJson)}
    >
      <MapLibreGL.Camera zoomLevel={20} centerCoordinate={[12.4768, 41.8986]} />
      <MapLibreGL.Animated.ImageSource
        key="d"
        id={"2"}
        coordinates={[
          [12.476275, 41.899308],
          [12.477344, 41.899327],
          [12.477386, 41.898122],
          [12.476319, 41.898102],
        ]}
        url={mapImage1}
      >
        <MapLibreGL.RasterLayer id="radarLayer" />
      </MapLibreGL.Animated.ImageSource>
    </MapLibreGL.MapView>
  );
}


```

i've attached the debug to the application and ImageSource is creating this url for the imported image  'http://localhost:8081/assets/map/1.png', if i'll activate the internet connection on the device the image is correctly displayed.

maybe i'm missing something, thanks :)

**Comment by jthiard** [comment]
`http://localhost:8081' is the uri of the metro server, used in debug mode to communicate with the device. In this mode the imported assets are served from this server to enable fast reload.

Did you try a release build ? I think in a release build the generated uri should be a local one.

**Comment by babeone** [comment]
Yeah you are right, in dev i can't see the image but doing the apk in release it work. Thank you :)
