### ISSUE TITLE
MapLibreGL.addCustomHeader(...) is not a function (it is undefined)

### ISSUE THREAD

**Issue by bryanvanwijk** [maplibre/maplibre-react-native#551]
### Steps to Trigger Behavior

Following the custom HTTP headers [docs](https://github.com/maplibre/maplibre-react-native/blob/main/docs/CustomHttpHeaders.md) and then actually adding it triggers an error.
```
import MapLibreGL from '@maplibre/maplibre-react-native';

MapLibreGL.addCustomHeader("Authorization", "{TOKEN}");
```

### Expected Behavior

The custom header is successfully set and the headers are included on the requests made afterwards.

### Actual Behavior

It triggers the following error: ` _maplibreReactNative.default.addCustomHeader is not a function (it is undefined)`

### Environment

- Platform: iOS
- OS version: iOS 18
- Device type: iPhone 14
- Emulator or Simulator: Yes and Physical device as well
- Development OS: macOS 15.1.1
- `@maplibre/maplibre-react-native` Version: 10.0.0-beta.7
- `react-native` Version: 0.74.5
- `expo` Version: 51.0.34

**Comment by tyrauber** [comment]
Huh, I am seeing the native methods, but no, javascript method for `addCustomHeader`.   @KiwiKilian, I same issue as #546, did we accidentally remove the js api for this method?

**Comment by KiwiKilian** [comment]
It only ever was a type definition, which seems to have been removed here: https://github.com/maplibre/maplibre-react-native/commit/764a3eb33fd9666b80f009968a905b2a287f6ad6#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L111

**Comment by tyrauber** [comment]
Yeah, I am seeing the same thing. I went back through tags all the way to 9.0.0 and it looks like there never was a javascript method?!? In 9.0.0 there was a typescript function declartion, but no js function.  I guess this was never implemented?

**Comment by KiwiKilian** [comment]
It only needs a passthrough from native, give me 5 minutes.
