### ISSUE TITLE
Remove Style Enums

### ISSUE THREAD

**Issue by KiwiKilian** [maplibre/maplibre-react-native#553]
We should move more towards the Style Spec of `maplibre-gl-js`, which doesn't have enums.

So we should move from this:

```ts
lineCap?: Value<Enum<LineCapEnum, LineCapEnumValues>, ["zoom"]>;
```

To:
```ts
lineCap?: Value<"butt" | "round" | "square", ["zoom"]>;
```

And remove the Enums.

**Comment by tyrauber** [comment]
Are those not the same? Bad copy / paste?

**Comment by KiwiKilian** [comment]
Sorry, copy-paste error. Updated the proposal.

**Comment by tyrauber** [comment]
Works for me.
