### ISSUE TITLE
Enable support for RTL Text

### ISSUE THREAD

**Issue by f1sh1918** [maplibre/maplibre-react-native#57]
## Motivation
Since we have users with arabic background we would like to be able to show text in arabic on the map.
For web maplibre js provides a RTL Plugin: https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-rtl-text/
For native it seems like there is no support. I even couldn't find.

## Design Alternatives

The feature could be provided with a separate plugin

## Design

The feature couldn't be implemented directly

### Mock-Up

<img width="618" alt="image" src="https://github.com/maplibre/maplibre-react-native/assets/37902063/bbe76d8a-1073-4137-abe6-6bc4a2761ce9">

### Concept

I don't have really design or concepts for this, since i don't know much about what has to be done but probably the features that are included in the js library could be ported to the native library

**Comment by Anwenden001** [comment]
Hey you can try if it works if you prefix the UTF RTL code:
`\u{200F}`
you can also try:
`\u200F`

https://unicodeplus.com/U+200F

https://stackoverflow.com/questions/59319997/how-to-set-direction-property-of-a-view-to-rtl-in-react-native

**Comment by f1sh1918** [comment]
okay it was basically an issue with the font glyphs on my side. Only changed on our web platform but not for native.
Thx for the hint

**Comment by Anwenden001** [comment]
oh that works? :D
was just a guess based on the standard
